import {defineField, defineType} from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Definições do site',
  type: 'document',
  groups: [
    {name: 'empresa', title: 'Empresa', default: true},
    {name: 'contactos', title: 'Contactos'},
    {name: 'redes', title: 'Redes sociais'},
    {name: 'seo', title: 'SEO e partilha'},
  ],
  fields: [
    defineField({
      name: 'razaoSocial',
      title: 'Razão social',
      type: 'string',
      group: 'empresa',
      description: 'Aparece no rodapé, sob o logótipo.',
    }),
    defineField({name: 'tagline', title: 'Assinatura', type: 'localeString', group: 'empresa'}),
    defineField({
      name: 'morada',
      title: 'Morada',
      type: 'text',
      rows: 2,
      group: 'contactos',
      description: 'Uma linha por linha de morada.',
    }),
    defineField({name: 'telefone', title: 'Telefone', type: 'string', group: 'contactos'}),
    defineField({
      name: 'whatsapp',
      title: 'WhatsApp',
      type: 'string',
      group: 'contactos',
      description: 'Número formatado, ex.: (+238) 955 10 20',
    }),
    defineField({
      name: 'whatsappUrl',
      title: 'Link do WhatsApp',
      type: 'url',
      group: 'contactos',
      description: 'Ex.: https://wa.me/2389551020',
    }),
    defineField({name: 'email', title: 'Email', type: 'string', group: 'contactos'}),
    defineField({name: 'horarioDias', title: 'Dias de abertura', type: 'localeString', group: 'contactos'}),
    defineField({
      name: 'horarioHoras',
      title: 'Horas de abertura',
      type: 'text',
      rows: 2,
      group: 'contactos',
      description: 'Uma linha por período, ex.: 08h00 – 13h00',
    }),
    defineField({name: 'mapaUrl', title: 'Link do mapa', type: 'url', group: 'contactos'}),
    defineField({name: 'facebook', title: 'Facebook', type: 'url', group: 'redes'}),
    defineField({name: 'instagram', title: 'Instagram', type: 'url', group: 'redes'}),
    defineField({name: 'linkedin', title: 'LinkedIn', type: 'url', group: 'redes'}),
    defineField({name: 'newsletterTexto', title: 'Texto da newsletter', type: 'localeString', group: 'empresa'}),
    defineField({name: 'copyright', title: 'Rodapé legal', type: 'localeString', group: 'empresa'}),
    defineField({
      name: 'ogImage',
      title: 'Imagem de partilha (1200×630)',
      type: 'figura',
      group: 'seo',
      description: 'Usada quando o site é partilhado em redes sociais e no WhatsApp.',
    }),
  ],
  preview: {prepare: () => ({title: 'Definições do site'})},
})
